name: Build with vcpkg

on:
  workflow_dispatch:          # manual "Run workflow" button
  push:
    branches: [ 7.72 ]

jobs:
  windows:
    name: windows-msvc-Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Remove preinstalled MySQL (avoids header conflicts)
        run: rm -r -fo C:/mysql-5.7.21-winx64
        continue-on-error: true

      - name: Set environment vars
        run: |
          echo "CXX=cl.exe" >> $GITHUB_ENV
          echo "CC=cl.exe" >> $GITHUB_ENV
        shell: bash

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgArguments: >
            boost-asio boost-iostreams boost-system boost-filesystem boost-variant boost-lockfree
            lua luajit libmariadb pugixml cryptopp fmt
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgTriplet: x64-windows
          vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092

      - name: Build with CMake
        uses: lukka/run-cmake@v3
        with:
          useVcpkgToolchainFile: true
          buildDirectory: ${{ runner.workspace }}/build
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: '-G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_LUAJIT=on'

      - name: Assemble server package
        run: |
          cp ${{ runner.workspace }}/build/tfs.exe .
          cp ${{ runner.workspace }}/build/*.dll .
        shell: bash

      - name: Upload server package
        uses: actions/upload-artifact@v4
        with:
          name: tfs-7.72-windows-release
          path: |
            tfs.exe
            *.dll
            data
            config.lua.dist
            schema.sql
            key.pem
